# Site settings
title: "Conor Chan's Blog"
email: rafikixx@yahoo.com
description: "Conor Chan's Blog."
baseurl: ""
url: "https://conorJChan.gitlab.io"
title_description: "A blog about Conor Chan."
title_image: "http://www.gravatar.com/avatar/5efdfcd39bcf7558d2a607040ef8bbe5"

# google_analytics: ""
disqus_account: ChanBaby
# github_repository: https://github.com/jacobtomlinson/carte-noire
# addthis_id: ra-513c6fa83da6ec67
post_limit: 25

# Social usernames/URLs
# twitter_username: _jacobtomlinson
# github_username:  jacobtomlinson
# linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
# google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
# stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
# gitlab_link: https://gitlab.com/jekyll-themes/carte-noire/



# Build settings
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
highlighter: rouge
